---
# Source: regorule-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regorule-operator-deployment
  labels:
    helm.sh/chart: regorule-operator-0.8.0-nightly
    app.kubernetes.io/name: regorule-operator
    app.kubernetes.io/instance: regorule-operator
    app.kubernetes.io/version: "0.8.0-nightly"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: regorule-operator
      app.kubernetes.io/instance: regorule-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: regorule-operator
        app.kubernetes.io/instance: regorule-operator
    spec:
      serviceAccountName: regorule-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: regorule-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/regorule-operator:0.8.0-nightly"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - mountPath: /etc/stackable/regorule-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: regorule-operator-configmap
