---
apiVersion: v1
kind: Service
metadata:
  name: regorule-operator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3030
      protocol: TCP
  selector:
    app.kubernetes.io/name: regorule-operator
    app.kubernetes.io/instance: regorule-operator
