---
# Source: regorule-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: regorule-operator-serviceaccount
  labels:
    helm.sh/chart: regorule-operator-0.6.0
    app.kubernetes.io/name: regorule-operator
    app.kubernetes.io/instance: regorule-operator
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: regorule-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: regorule-operator-clusterrolebinding
  labels:
    helm.sh/chart: regorule-operator-0.6.0
    app.kubernetes.io/name: regorule-operator
    app.kubernetes.io/instance: regorule-operator
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: regorule-operator-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: regorule-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
