= Stackable RegoRule Operator

This Kubernetes Operator supports a CRD named `RegoRule`.

Rego is the language used to define policies in the https://www.openpolicyagent.org/[OpenPolicyAgent].

This Operator will watch for new rules and will create a bundle out of all rules in the watched namespace and will make it available via a simple web server under the URL `opa/v1/opa/bundle.tar.gz`.
You can find examples in the `example` directory and the CRD yaml is in `deploy/crd`.

NOTE: There is - at the moment - no validation of the rules at all. You need to make sure to include a valid `package` statement, the operator does not check for conflicts.

NOTE: Currently, the bundle file will be created on disk in the current working directory.

== Building

This operator is written in Rust.
It is developed against the latest Rust release (1.51 at the time of writing this), earlier versions might work but are untested.

    cargo build --release

== Running

Build it first, the binary will be in `target/release`.

.You can start it like this:
[source]
----
# Defaults
stackable-regorule-operator-server

# Change port for webserver
stackable-regorule-operator-server --port 1234

# Change namespace to watch, if unspecified it'll watch all namespaces
export WATCH_NAMESPACE=foobar
stackable-regorule-operator-server --port 1234
----

== Configuring OPA

You need to configure OPA to query our server.

.Example configuration snippet: `config.yaml`
[source,yaml]
----
services:
  - name: stackable
    url: http://localhost:3030/opa/v1

bundles:
  stackable:
    service: stackable
    resource: opa/bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20
----

You can then run OPA like this:

    opa run -s -c config.yaml
