apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3030
    protocol: TCP
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
